dist: trusty
sudo: false

language: python

cache:
  directories:
  - $HOME/.cache/pip


matrix:
  include:
    - env: PYTHON_VERSION="3.6"
    - env: PYTHON_VERSION="3.7"


before_install:
  # install miniconda

  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda update --yes --quiet conda

  # create the testing environment
  - conda env create --file environment.yml python=${PYTHON_VERSION}
  - source activate groupmne-env
  - conda install --yes --quiet pytest pytest-cov coverage
  - pip install flake8 check-manifest
  - pip install codecov

install:
  - python setup.py build_ext --inplace
  - pip install -e .

script:
  - pytest -lv --cov-report term-missing groupmne --cov=groupmne --cov-config .coveragerc
  - make
  - flake8 --count groupmne
after_success:
  - cp .coverage $TRAVIS_BUILD_DIR
  - codecov --root $TRAVIS_BUILD_DIR || echo "codecov upload failed"
