name: groupmne

dependencies:
    - pip=19.1.1
    - numpy
    - scipy
    - matplotlib
    - joblib
    - numba
    - pytest
    - pip:
        - vtk
        - https://api.github.com/repos/enthought/mayavi/zipball/e2569be1096be3deecb15f8fa8581a3ae3fb77d3
        - mne
        - PySurfer[save_movie]
